//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageSite
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ImageReported> ImageReported { get; set; }
        public DbSet<ReportedCommentAdded> ReportedCommentAdded { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<UserAuthentication> UserAuthentication { get; set; }
        public DbSet<UserDislikeAdded> UserDislikeAdded { get; set; }
        public DbSet<UserDislikeCommentAdded> UserDislikeCommentAdded { get; set; }
        public DbSet<UserLike> UserLike { get; set; }
        public DbSet<UserLikeCommentAdded> UserLikeCommentAdded { get; set; }
        public DbSet<UserRelatedComment> UserRelatedComment { get; set; }
        public DbSet<UserRelatedImage> UserRelatedImage { get; set; }
    }
}
