//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageReported
    {
        public int ReportedImageID { get; set; }
        public Nullable<int> ImageReported1 { get; set; }
        public Nullable<System.DateTime> DateImageReported { get; set; }
        public string UserComImageReport { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> UserImageID { get; set; }
    
        public virtual UserAuthentication UserAuthentication { get; set; }
        public virtual UserRelatedImage UserRelatedImage { get; set; }
    }
}
