//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDislikeAdded
    {
        public int UserDislikeID { get; set; }
        public Nullable<int> UserDislike { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual UserAuthentication UserAuthentication { get; set; }
    }
}
