//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRelatedComment
    {
        public UserRelatedComment()
        {
            this.ReportedCommentAdded = new HashSet<ReportedCommentAdded>();
            this.UserDislikeCommentAdded = new HashSet<UserDislikeCommentAdded>();
            this.UserLikeCommentAdded = new HashSet<UserLikeCommentAdded>();
        }
    
        public int UserCommentID { get; set; }
        public string UserComment { get; set; }
        public Nullable<System.DateTime> DateCommentAdded { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual ICollection<ReportedCommentAdded> ReportedCommentAdded { get; set; }
        public virtual UserAuthentication UserAuthentication { get; set; }
        public virtual ICollection<UserDislikeCommentAdded> UserDislikeCommentAdded { get; set; }
        public virtual ICollection<UserLikeCommentAdded> UserLikeCommentAdded { get; set; }
    }
}
