//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAuthentication
    {
        public UserAuthentication()
        {
            this.ImageReported = new HashSet<ImageReported>();
            this.ReportedCommentAdded = new HashSet<ReportedCommentAdded>();
            this.UserDislikeAdded = new HashSet<UserDislikeAdded>();
            this.UserDislikeCommentAdded = new HashSet<UserDislikeCommentAdded>();
            this.UserLike = new HashSet<UserLike>();
            this.UserLikeCommentAdded = new HashSet<UserLikeCommentAdded>();
            this.UserRelatedComment = new HashSet<UserRelatedComment>();
            this.UserRelatedImage = new HashSet<UserRelatedImage>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string UserEmail { get; set; }
    
        public virtual ICollection<ImageReported> ImageReported { get; set; }
        public virtual ICollection<ReportedCommentAdded> ReportedCommentAdded { get; set; }
        public virtual ICollection<UserDislikeAdded> UserDislikeAdded { get; set; }
        public virtual ICollection<UserDislikeCommentAdded> UserDislikeCommentAdded { get; set; }
        public virtual ICollection<UserLike> UserLike { get; set; }
        public virtual ICollection<UserLikeCommentAdded> UserLikeCommentAdded { get; set; }
        public virtual ICollection<UserRelatedComment> UserRelatedComment { get; set; }
        public virtual ICollection<UserRelatedImage> UserRelatedImage { get; set; }
    }
}
